// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZimraFdms.Api.Data;

#nullable disable

namespace ZimraFdms.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ZimraFdms.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZimraFdms.Api.Data.Entities.DeviceOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceOperators");
                });

            modelBuilder.Entity("ZimraFdms.Api.Data.Entities.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificatePfxPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceModelVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceSerialNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKeyPemPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueDbPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseEcc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ZimraFdms.Api.Data.Entities.AppUser", b =>
                {
                    b.HasOne("ZimraFdms.Api.Data.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ZimraFdms.Api.Data.Entities.DeviceOperator", b =>
                {
                    b.HasOne("ZimraFdms.Api.Data.Entities.UserDevice", "Device")
                        .WithMany("Operators")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZimraFdms.Api.Data.Entities.AppUser", "User")
                        .WithMany("DeviceAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZimraFdms.Api.Data.Entities.UserDevice", b =>
                {
                    b.HasOne("ZimraFdms.Api.Data.Entities.AppUser", "Owner")
                        .WithMany("OwnedDevices")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ZimraFdms.Api.Data.Entities.AppUser", b =>
                {
                    b.Navigation("DeviceAssignments");

                    b.Navigation("OwnedDevices");
                });

            modelBuilder.Entity("ZimraFdms.Api.Data.Entities.UserDevice", b =>
                {
                    b.Navigation("Operators");
                });
#pragma warning restore 612, 618
        }
    }
}
